#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("wincom.mobile.erp.Resource", IsApplication=true)]

namespace wincom.mobile.erp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070002
			public const int papersize_array = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int printer_array = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int term = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int trxtype = 2131165184;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040009
			public const int ab_background = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int ab_bottom_shadow_1 = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int ab_bottom_shadow_2 = 2130968587;
			
			// aapt resource value: 0x7f040008
			public const int action_bar_title_color = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int bluethem_color = 2130968582;
			
			// aapt resource value: 0x7f04000c
			public const int btn_bg_color = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int btn_bg_shadow_color = 2130968589;
			
			// aapt resource value: 0x7f040007
			public const int main_background = 2130968583;
			
			// aapt resource value: 0x7f040001
			public const int xam_blue = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int xam_dark_blue = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int xam_gray = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int xam_green = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int xam_light_gray = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int xam_purple = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050001
			public const int btn_corner_radius = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int tab_host_default_height = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ab_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int about = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int add = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Bill = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bluethem_activated_background_holo_light = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bluethem_btn_default_disabled_focused_holo_light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int bluethem_btn_default_disabled_holo_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int bluethem_btn_default_focused_holo_light = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int bluethem_btn_default_holo_light = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int bluethem_btn_default_normal_holo_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int bluethem_btn_default_pressed_holo_light = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int bluethem_edit_text_holo_light = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int bluethem_fastscroll_thumb_default_holo = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int bluethem_fastscroll_thumb_pressed_holo = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int bluethem_list_activated_holo = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int bluethem_list_focused_holo = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int bluethem_list_longpressed_holo = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int bluethem_list_pressed_holo_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int bluethem_list_selector_background_transition_holo_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int bluethem_list_selector_disabled_holo_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int bluethem_list_selector_holo_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int bluethem_spinner_background_holo_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int bluethem_spinner_default_holo_light = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int bluethem_spinner_disabled_holo_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int bluethem_spinner_focused_holo_light = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int bluethem_spinner_pressed_holo_light = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int bluethem_textfield_activated_holo_light = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int bluethem_textfield_default_holo_light = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int bluethem_textfield_disabled_focused_holo_light = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int bluethem_textfield_disabled_holo_light = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int bluethem_textfield_focused_holo_light = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int btn_bg = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int btn_bg_inactive = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int btn_bg_normal = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int btn_bg_pressed = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int create = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int delivery = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int discrete_shadow = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int download = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int even_row = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int exit = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int home = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ic_action_logo = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int Icon = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int item = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int left = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int listview_selector_even = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int listview_selector_odd = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int logo = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int odd_row = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int ok = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int print = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int printer_blue = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int report = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int Sales = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int settings = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int shop = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int shoplist = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int star = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int summary = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int trader = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int upload = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int wrench = 2130837566;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0029
			public const int Cancel = 2131361833;
			
			// aapt resource value: 0x7f0a0078
			public const int CustList = 2131361912;
			
			// aapt resource value: 0x7f0a002d
			public const int Home = 2131361837;
			
			// aapt resource value: 0x7f0a006c
			public const int ICodeList = 2131361900;
			
			// aapt resource value: 0x7f0a0099
			public const int List = 2131361945;
			
			// aapt resource value: 0x7f0a002c
			public const int NewBill = 2131361836;
			
			// aapt resource value: 0x7f0a002b
			public const int Paid = 2131361835;
			
			// aapt resource value: 0x7f0a002a
			public const int Print = 2131361834;
			
			// aapt resource value: 0x7f0a0028
			public const int Save = 2131361832;
			
			// aapt resource value: 0x7f0a007f
			public const int TaxAmount = 2131361919;
			
			// aapt resource value: 0x7f0a007d
			public const int TtlAmount = 2131361917;
			
			// aapt resource value: 0x7f0a0000
			public const int about_credits = 2131361792;
			
			// aapt resource value: 0x7f0a0002
			public const int about_descrip = 2131361794;
			
			// aapt resource value: 0x7f0a0001
			public const int about_ver = 2131361793;
			
			// aapt resource value: 0x7f0a0018
			public const int ad_Cancel = 2131361816;
			
			// aapt resource value: 0x7f0a0017
			public const int ad_bSave = 2131361815;
			
			// aapt resource value: 0x7f0a00c5
			public const int add = 2131361989;
			
			// aapt resource value: 0x7f0a001b
			public const int bfindCust = 2131361819;
			
			// aapt resource value: 0x7f0a0020
			public const int bfindItem = 2131361824;
			
			// aapt resource value: 0x7f0a0073
			public const int btnItem_OK = 2131361907;
			
			// aapt resource value: 0x7f0a00b2
			public const int btnTrd_OK = 2131361970;
			
			// aapt resource value: 0x7f0a00a1
			public const int butAbout = 2131361953;
			
			// aapt resource value: 0x7f0a00b4
			public const int butCNlist = 2131361972;
			
			// aapt resource value: 0x7f0a0086
			public const int butCash = 2131361926;
			
			// aapt resource value: 0x7f0a00b3
			public const int butCashlist = 2131361971;
			
			// aapt resource value: 0x7f0a0077
			public const int butCustBack = 2131361911;
			
			// aapt resource value: 0x7f0a0090
			public const int butCustProf = 2131361936;
			
			// aapt resource value: 0x7f0a00b5
			public const int butDOlist = 2131361973;
			
			// aapt resource value: 0x7f0a0049
			public const int butDown = 2131361865;
			
			// aapt resource value: 0x7f0a004a
			public const int butDownCust = 2131361866;
			
			// aapt resource value: 0x7f0a004b
			public const int butDownSetting = 2131361867;
			
			// aapt resource value: 0x7f0a006a
			public const int butICodeBack = 2131361898;
			
			// aapt resource value: 0x7f0a0082
			public const int butInvBack = 2131361922;
			
			// aapt resource value: 0x7f0a0060
			public const int butInvItmBack = 2131361888;
			
			// aapt resource value: 0x7f0a008b
			public const int butInvlist = 2131361931;
			
			// aapt resource value: 0x7f0a00b7
			public const int butInvsumm = 2131361975;
			
			// aapt resource value: 0x7f0a004c
			public const int butMain = 2131361868;
			
			// aapt resource value: 0x7f0a008c
			public const int butMaster = 2131361932;
			
			// aapt resource value: 0x7f0a008f
			public const int butOut = 2131361935;
			
			// aapt resource value: 0x7f0a0085
			public const int butPOS = 2131361925;
			
			// aapt resource value: 0x7f0a00b6
			public const int butSOlist = 2131361974;
			
			// aapt resource value: 0x7f0a0087
			public const int butSecond = 2131361927;
			
			// aapt resource value: 0x7f0a0088
			public const int butcnnote = 2131361928;
			
			// aapt resource value: 0x7f0a0089
			public const int butdo = 2131361929;
			
			// aapt resource value: 0x7f0a0083
			public const int butnewInv = 2131361923;
			
			// aapt resource value: 0x7f0a0061
			public const int butnewItem = 2131361889;
			
			// aapt resource value: 0x7f0a0046
			public const int butok = 2131361862;
			
			// aapt resource value: 0x7f0a008e
			public const int butsetting = 2131361934;
			
			// aapt resource value: 0x7f0a008a
			public const int butso = 2131361930;
			
			// aapt resource value: 0x7f0a00a0
			public const int buttestprint = 2131361952;
			
			// aapt resource value: 0x7f0a009f
			public const int button1 = 2131361951;
			
			// aapt resource value: 0x7f0a008d
			public const int butupload = 2131361933;
			
			// aapt resource value: 0x7f0a00bb
			public const int butuploadAll = 2131361979;
			
			// aapt resource value: 0x7f0a00b8
			public const int butuploadcn = 2131361976;
			
			// aapt resource value: 0x7f0a00ba
			public const int butuploaddo = 2131361978;
			
			// aapt resource value: 0x7f0a00b9
			public const int butuploadso = 2131361977;
			
			// aapt resource value: 0x7f0a00c8
			public const int call = 2131361992;
			
			// aapt resource value: 0x7f0a005b
			public const int content = 2131361883;
			
			// aapt resource value: 0x7f0a001a
			public const int custcode = 2131361818;
			
			// aapt resource value: 0x7f0a0074
			public const int custname = 2131361908;
			
			// aapt resource value: 0x7f0a009c
			public const int editText1 = 2131361948;
			
			// aapt resource value: 0x7f0a00a6
			public const int exit = 2131361958;
			
			// aapt resource value: 0x7f0a0084
			public const int feedList = 2131361924;
			
			// aapt resource value: 0x7f0a005a
			public const int footer = 2131361882;
			
			// aapt resource value: 0x7f0a004d
			public const int header = 2131361869;
			
			// aapt resource value: 0x7f0a0064
			public const int icodecode = 2131361892;
			
			// aapt resource value: 0x7f0a0063
			public const int icodedesc = 2131361891;
			
			// aapt resource value: 0x7f0a0068
			public const int icodeinclusive = 2131361896;
			
			// aapt resource value: 0x7f0a0065
			public const int icodeprice = 2131361893;
			
			// aapt resource value: 0x7f0a0066
			public const int icodetax = 2131361894;
			
			// aapt resource value: 0x7f0a0067
			public const int icodetaxper = 2131361895;
			
			// aapt resource value: 0x7f0a007e
			public const int invcust = 2131361918;
			
			// aapt resource value: 0x7f0a0079
			public const int invdate = 2131361913;
			
			// aapt resource value: 0x7f0a0034
			public const int invitemList = 2131361844;
			
			// aapt resource value: 0x7f0a005e
			public const int invitemTemp1 = 2131361886;
			
			// aapt resource value: 0x7f0a005f
			public const int invitemTemp2 = 2131361887;
			
			// aapt resource value: 0x7f0a0033
			public const int invitemamt = 2131361843;
			
			// aapt resource value: 0x7f0a002e
			public const int invitemcode = 2131361838;
			
			// aapt resource value: 0x7f0a005d
			public const int invitemdesc = 2131361885;
			
			// aapt resource value: 0x7f0a0030
			public const int invitemprice = 2131361840;
			
			// aapt resource value: 0x7f0a002f
			public const int invitemqty = 2131361839;
			
			// aapt resource value: 0x7f0a0032
			public const int invitemtax = 2131361842;
			
			// aapt resource value: 0x7f0a0031
			public const int invitemtaxgrp = 2131361841;
			
			// aapt resource value: 0x7f0a007a
			public const int invno = 2131361914;
			
			// aapt resource value: 0x7f0a0081
			public const int invremark = 2131361921;
			
			// aapt resource value: 0x7f0a000f
			public const int lbCNPrefix = 2131361807;
			
			// aapt resource value: 0x7f0a000d
			public const int lbCashPrefix = 2131361805;
			
			// aapt resource value: 0x7f0a0013
			public const int lbDOPrefix = 2131361811;
			
			// aapt resource value: 0x7f0a000b
			public const int lbInvPrefix = 2131361803;
			
			// aapt resource value: 0x7f0a0008
			public const int lbPaper = 2131361800;
			
			// aapt resource value: 0x7f0a0011
			public const int lbSOPrefix = 2131361809;
			
			// aapt resource value: 0x7f0a0041
			public const int lbbillto = 2131361857;
			
			// aapt resource value: 0x7f0a0005
			public const int lbinvno = 2131361797;
			
			// aapt resource value: 0x7f0a003d
			public const int lbinvnotype = 2131361853;
			
			// aapt resource value: 0x7f0a0003
			public const int lbprinter = 2131361795;
			
			// aapt resource value: 0x7f0a005c
			public const int linearLayout1 = 2131361884;
			
			// aapt resource value: 0x7f0a004e
			public const int linearLayout10 = 2131361870;
			
			// aapt resource value: 0x7f0a0050
			public const int linearLayout2 = 2131361872;
			
			// aapt resource value: 0x7f0a0098
			public const int linearLayout3 = 2131361944;
			
			// aapt resource value: 0x7f0a0054
			public const int linearLayout4 = 2131361876;
			
			// aapt resource value: 0x7f0a0055
			public const int linearLayout5 = 2131361877;
			
			// aapt resource value: 0x7f0a0056
			public const int linearLayout6 = 2131361878;
			
			// aapt resource value: 0x7f0a0057
			public const int linearLayout7 = 2131361879;
			
			// aapt resource value: 0x7f0a0058
			public const int linearLayout8 = 2131361880;
			
			// aapt resource value: 0x7f0a0059
			public const int linearLayout9 = 2131361881;
			
			// aapt resource value: 0x7f0a004f
			public const int linearLayoutCS = 2131361871;
			
			// aapt resource value: 0x7f0a0080
			public const int linearLayoutRmark = 2131361920;
			
			// aapt resource value: 0x7f0a0062
			public const int linearLayoutTitle = 2131361890;
			
			// aapt resource value: 0x7f0a00a8
			public const int logimport = 2131361960;
			
			// aapt resource value: 0x7f0a00a5
			public const int login = 2131361957;
			
			// aapt resource value: 0x7f0a00a4
			public const int login_code = 2131361956;
			
			// aapt resource value: 0x7f0a00a3
			public const int login_password = 2131361955;
			
			// aapt resource value: 0x7f0a00a2
			public const int login_userName = 2131361954;
			
			// aapt resource value: 0x7f0a00c4
			public const int mainMenu = 2131361988;
			
			// aapt resource value: 0x7f0a00bf
			public const int mmenu_back = 2131361983;
			
			// aapt resource value: 0x7f0a00c1
			public const int mmenu_clear = 2131361985;
			
			// aapt resource value: 0x7f0a00bc
			public const int mmenu_downcompinfo = 2131361980;
			
			// aapt resource value: 0x7f0a00bd
			public const int mmenu_downdb = 2131361981;
			
			// aapt resource value: 0x7f0a00c0
			public const int mmenu_downlogo = 2131361984;
			
			// aapt resource value: 0x7f0a00be
			public const int mmenu_downtmp = 2131361982;
			
			// aapt resource value: 0x7f0a00c3
			public const int mmenu_logoff = 2131361987;
			
			// aapt resource value: 0x7f0a00c2
			public const int mmenu_setting = 2131361986;
			
			// aapt resource value: 0x7f0a0037
			public const int newcninv_no = 2131361847;
			
			// aapt resource value: 0x7f0a003a
			public const int newinv_bfind = 2131361850;
			
			// aapt resource value: 0x7f0a0038
			public const int newinv_bfindinv = 2131361848;
			
			// aapt resource value: 0x7f0a0043
			public const int newinv_billfind = 2131361859;
			
			// aapt resource value: 0x7f0a0042
			public const int newinv_billto = 2131361858;
			
			// aapt resource value: 0x7f0a003b
			public const int newinv_bsave = 2131361851;
			
			// aapt resource value: 0x7f0a003c
			public const int newinv_cancel = 2131361852;
			
			// aapt resource value: 0x7f0a0039
			public const int newinv_custcode = 2131361849;
			
			// aapt resource value: 0x7f0a001c
			public const int newinv_custname = 2131361820;
			
			// aapt resource value: 0x7f0a0035
			public const int newinv_date = 2131361845;
			
			// aapt resource value: 0x7f0a0036
			public const int newinv_no = 2131361846;
			
			// aapt resource value: 0x7f0a0040
			public const int newinv_po = 2131361856;
			
			// aapt resource value: 0x7f0a003f
			public const int newinv_remark = 2131361855;
			
			// aapt resource value: 0x7f0a003e
			public const int newinv_type = 2131361854;
			
			// aapt resource value: 0x7f0a0091
			public const int newinvno = 2131361937;
			
			// aapt resource value: 0x7f0a009e
			public const int numberPicker1 = 2131361950;
			
			// aapt resource value: 0x7f0a0092
			public const int payamt = 2131361938;
			
			// aapt resource value: 0x7f0a0095
			public const int paycash = 2131361941;
			
			// aapt resource value: 0x7f0a0096
			public const int paychange = 2131361942;
			
			// aapt resource value: 0x7f0a0097
			public const int payok = 2131361943;
			
			// aapt resource value: 0x7f0a0093
			public const int payround = 2131361939;
			
			// aapt resource value: 0x7f0a0094
			public const int paytotal = 2131361940;
			
			// aapt resource value: 0x7f0a00c6
			public const int phone = 2131361990;
			
			// aapt resource value: 0x7f0a00cd
			public const int popInvadd = 2131361997;
			
			// aapt resource value: 0x7f0a00cf
			public const int popInvdelete = 2131361999;
			
			// aapt resource value: 0x7f0a00ce
			public const int popInvedit = 2131361998;
			
			// aapt resource value: 0x7f0a00ca
			public const int popInvfilter = 2131361994;
			
			// aapt resource value: 0x7f0a00cb
			public const int popInvprint = 2131361995;
			
			// aapt resource value: 0x7f0a00cc
			public const int popInvprint2 = 2131361996;
			
			// aapt resource value: 0x7f0a00d1
			public const int popadd = 2131362001;
			
			// aapt resource value: 0x7f0a00d3
			public const int popdelete = 2131362003;
			
			// aapt resource value: 0x7f0a00d2
			public const int popedit = 2131362002;
			
			// aapt resource value: 0x7f0a00d0
			public const int poppay = 2131362000;
			
			// aapt resource value: 0x7f0a007c
			public const int printed = 2131361916;
			
			// aapt resource value: 0x7f0a009a
			public const int printsumm = 2131361946;
			
			// aapt resource value: 0x7f0a009b
			public const int printsumm_cancel = 2131361947;
			
			// aapt resource value: 0x7f0a00c9
			public const int refresh = 2131361993;
			
			// aapt resource value: 0x7f0a00c7
			public const int submenu = 2131361991;
			
			// aapt resource value: 0x7f0a0015
			public const int tableLayout1 = 2131361813;
			
			// aapt resource value: 0x7f0a0069
			public const int tableLayoutItem = 2131361897;
			
			// aapt resource value: 0x7f0a0075
			public const int tableLayoutItemc = 2131361909;
			
			// aapt resource value: 0x7f0a0016
			public const int tableRow1 = 2131361814;
			
			// aapt resource value: 0x7f0a0076
			public const int tableRow1c = 2131361910;
			
			// aapt resource value: 0x7f0a0019
			public const int tableRow2 = 2131361817;
			
			// aapt resource value: 0x7f0a00a7
			public const int textVer = 2131361959;
			
			// aapt resource value: 0x7f0a001d
			public const int textView1 = 2131361821;
			
			// aapt resource value: 0x7f0a009d
			public const int textView2 = 2131361949;
			
			// aapt resource value: 0x7f0a0021
			public const int textView4 = 2131361825;
			
			// aapt resource value: 0x7f0a0022
			public const int textView5 = 2131361826;
			
			// aapt resource value: 0x7f0a0044
			public const int trxdatefr = 2131361860;
			
			// aapt resource value: 0x7f0a0045
			public const int trxdateto = 2131361861;
			
			// aapt resource value: 0x7f0a007b
			public const int trxtype = 2131361915;
			
			// aapt resource value: 0x7f0a0010
			public const int txtCNPrefix = 2131361808;
			
			// aapt resource value: 0x7f0a000e
			public const int txtCashPrefix = 2131361806;
			
			// aapt resource value: 0x7f0a0014
			public const int txtDOPrefix = 2131361812;
			
			// aapt resource value: 0x7f0a000c
			public const int txtInvPrefix = 2131361804;
			
			// aapt resource value: 0x7f0a0048
			public const int txtInvcust = 2131361864;
			
			// aapt resource value: 0x7f0a0052
			public const int txtInvdate = 2131361874;
			
			// aapt resource value: 0x7f0a0053
			public const int txtInvmode = 2131361875;
			
			// aapt resource value: 0x7f0a0051
			public const int txtInvno = 2131361873;
			
			// aapt resource value: 0x7f0a0047
			public const int txtInvnp = 2131361863;
			
			// aapt resource value: 0x7f0a0012
			public const int txtSOPrefix = 2131361810;
			
			// aapt resource value: 0x7f0a006b
			public const int txtSearch = 2131361899;
			
			// aapt resource value: 0x7f0a0009
			public const int txtSize = 2131361801;
			
			// aapt resource value: 0x7f0a0007
			public const int txtad_printer = 2131361799;
			
			// aapt resource value: 0x7f0a0026
			public const int txtamount = 2131361830;
			
			// aapt resource value: 0x7f0a001e
			public const int txtbarcode = 2131361822;
			
			// aapt resource value: 0x7f0a001f
			public const int txtcode = 2131361823;
			
			// aapt resource value: 0x7f0a00ab
			public const int txtcust_addr1 = 2131361963;
			
			// aapt resource value: 0x7f0a00ac
			public const int txtcust_addr2 = 2131361964;
			
			// aapt resource value: 0x7f0a00ad
			public const int txtcust_addr3 = 2131361965;
			
			// aapt resource value: 0x7f0a00ae
			public const int txtcust_addr4 = 2131361966;
			
			// aapt resource value: 0x7f0a00a9
			public const int txtcust_code = 2131361961;
			
			// aapt resource value: 0x7f0a00b0
			public const int txtcust_fax = 2131361968;
			
			// aapt resource value: 0x7f0a00b1
			public const int txtcust_gst = 2131361969;
			
			// aapt resource value: 0x7f0a00aa
			public const int txtcust_name = 2131361962;
			
			// aapt resource value: 0x7f0a00af
			public const int txtcust_tel = 2131361967;
			
			// aapt resource value: 0x7f0a006e
			public const int txtitem_code = 2131361902;
			
			// aapt resource value: 0x7f0a006d
			public const int txtitem_desc = 2131361901;
			
			// aapt resource value: 0x7f0a0072
			public const int txtitem_incl = 2131361906;
			
			// aapt resource value: 0x7f0a006f
			public const int txtitem_price = 2131361903;
			
			// aapt resource value: 0x7f0a0071
			public const int txtitem_tax = 2131361905;
			
			// aapt resource value: 0x7f0a0070
			public const int txtitem_taxgrop = 2131361904;
			
			// aapt resource value: 0x7f0a0024
			public const int txtprice = 2131361828;
			
			// aapt resource value: 0x7f0a000a
			public const int txtprinterip = 2131361802;
			
			// aapt resource value: 0x7f0a0006
			public const int txtprinters = 2131361798;
			
			// aapt resource value: 0x7f0a0004
			public const int txtprintertype = 2131361796;
			
			// aapt resource value: 0x7f0a0023
			public const int txtqty = 2131361827;
			
			// aapt resource value: 0x7f0a0025
			public const int txttax = 2131361829;
			
			// aapt resource value: 0x7f0a0027
			public const int txttaxamt = 2131361831;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int About = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AdPara = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CashEntry = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CreateCNote = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int CreateDO = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int CreateInvoice = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int CreateSO = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int DateRange = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int DOEntry = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Download = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Entry = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int EntryEx = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int InvDtlItemView = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int InvDtlItemViewCS = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int InvDtlView = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int ItemCodeDtlList = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int ItemCodeEntry = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int ItemCodeList = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int ItemInfo = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int ListCustDtlView = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int ListCustView = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int ListItemRow = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int ListItemRowCN = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int ListView = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int Main = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int MasterRef = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int Payment = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int POSCashEntry = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int PrintInvSumm = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int Second = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int Settings = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int SignIn = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int SimpleSpinnerDropDownItemEx = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int SOEntry = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int spinner_item = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int TraderInfo = 2130903075;
			
			// aapt resource value: 0x7f030024
			public const int Translist = 2130903076;
			
			// aapt resource value: 0x7f030025
			public const int Upload = 2130903077;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int MainMenu = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int menu = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int popupHis = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int popupInv = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int popupItem = 2131296260;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060002
			public const int app_credits = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int app_descrip = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060039
			public const int but_login = 2131099705;
			
			// aapt resource value: 0x7f06003a
			public const int but_save = 2131099706;
			
			// aapt resource value: 0x7f060091
			public const int button_Paid = 2131099793;
			
			// aapt resource value: 0x7f06002f
			public const int button_add = 2131099695;
			
			// aapt resource value: 0x7f060031
			public const int button_back = 2131099697;
			
			// aapt resource value: 0x7f06003c
			public const int button_bills = 2131099708;
			
			// aapt resource value: 0x7f060032
			public const int button_cancel = 2131099698;
			
			// aapt resource value: 0x7f060033
			public const int button_new = 2131099699;
			
			// aapt resource value: 0x7f060034
			public const int button_newitem = 2131099700;
			
			// aapt resource value: 0x7f060030
			public const int button_ok = 2131099696;
			
			// aapt resource value: 0x7f06003d
			public const int button_paid = 2131099709;
			
			// aapt resource value: 0x7f06003e
			public const int button_paidprint = 2131099710;
			
			// aapt resource value: 0x7f060035
			public const int button_print = 2131099701;
			
			// aapt resource value: 0x7f06003b
			public const int button_search = 2131099707;
			
			// aapt resource value: 0x7f06008d
			public const int form_billto = 2131099789;
			
			// aapt resource value: 0x7f06008c
			public const int form_custpono = 2131099788;
			
			// aapt resource value: 0x7f06008e
			public const int form_remark = 2131099790;
			
			// aapt resource value: 0x7f06008b
			public const int form_sono = 2131099787;
			
			// aapt resource value: 0x7f06002e
			public const int invform_amount = 2131099694;
			
			// aapt resource value: 0x7f060026
			public const int invform_cnno = 2131099686;
			
			// aapt resource value: 0x7f060029
			public const int invform_cust = 2131099689;
			
			// aapt resource value: 0x7f060025
			public const int invform_dono = 2131099685;
			
			// aapt resource value: 0x7f060023
			public const int invform_invno = 2131099683;
			
			// aapt resource value: 0x7f06002a
			public const int invform_item = 2131099690;
			
			// aapt resource value: 0x7f06002b
			public const int invform_qty = 2131099691;
			
			// aapt resource value: 0x7f060024
			public const int invform_sono = 2131099684;
			
			// aapt resource value: 0x7f06002d
			public const int invform_tax = 2131099693;
			
			// aapt resource value: 0x7f060028
			public const int invform_term = 2131099688;
			
			// aapt resource value: 0x7f060022
			public const int invform_trxdate = 2131099682;
			
			// aapt resource value: 0x7f060027
			public const int invform_type = 2131099687;
			
			// aapt resource value: 0x7f06002c
			public const int invform_uprice = 2131099692;
			
			// aapt resource value: 0x7f060063
			public const int list_amount = 2131099747;
			
			// aapt resource value: 0x7f06005f
			public const int list_itemcode = 2131099743;
			
			// aapt resource value: 0x7f060061
			public const int list_price = 2131099745;
			
			// aapt resource value: 0x7f060060
			public const int list_qty = 2131099744;
			
			// aapt resource value: 0x7f060062
			public const int list_taxamt = 2131099746;
			
			// aapt resource value: 0x7f060038
			public const int login_code = 2131099704;
			
			// aapt resource value: 0x7f060037
			public const int login_pass = 2131099703;
			
			// aapt resource value: 0x7f060036
			public const int login_userid = 2131099702;
			
			// aapt resource value: 0x7f060009
			public const int mainmenu_about = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int mainmenu_downupload = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int mainmenu_exit = 2131099658;
			
			// aapt resource value: 0x7f060005
			public const int mainmenu_master = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int mainmenu_settings = 2131099656;
			
			// aapt resource value: 0x7f060003
			public const int mainmenu_trx = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int mainmenu_trxlist = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int mainmenu_upload = 2131099655;
			
			// aapt resource value: 0x7f06007d
			public const int msg_accessdenied = 2131099773;
			
			// aapt resource value: 0x7f06008a
			public const int msg_bluetootherror = 2131099786;
			
			// aapt resource value: 0x7f060089
			public const int msg_bluetoothfound = 2131099785;
			
			// aapt resource value: 0x7f060088
			public const int msg_bluetoothnofound = 2131099784;
			
			// aapt resource value: 0x7f060086
			public const int msg_confirmcleer = 2131099782;
			
			// aapt resource value: 0x7f060085
			public const int msg_confirmdelete = 2131099781;
			
			// aapt resource value: 0x7f060087
			public const int msg_confirmoverwrite = 2131099783;
			
			// aapt resource value: 0x7f06006a
			public const int msg_downcust = 2131099754;
			
			// aapt resource value: 0x7f060069
			public const int msg_downitem = 2131099753;
			
			// aapt resource value: 0x7f060070
			public const int msg_downsettings = 2131099760;
			
			// aapt resource value: 0x7f06007b
			public const int msg_faildowndb = 2131099771;
			
			// aapt resource value: 0x7f06007c
			public const int msg_faildownlogo = 2131099772;
			
			// aapt resource value: 0x7f06007a
			public const int msg_faildowntmp = 2131099770;
			
			// aapt resource value: 0x7f060067
			public const int msg_faillogin = 2131099751;
			
			// aapt resource value: 0x7f060080
			public const int msg_invalidcust = 2131099776;
			
			// aapt resource value: 0x7f06007f
			public const int msg_invaliddate = 2131099775;
			
			// aapt resource value: 0x7f060081
			public const int msg_invaliditem = 2131099777;
			
			// aapt resource value: 0x7f060083
			public const int msg_invalidprice = 2131099779;
			
			// aapt resource value: 0x7f060082
			public const int msg_invalidqty = 2131099778;
			
			// aapt resource value: 0x7f060084
			public const int msg_itemadded = 2131099780;
			
			// aapt resource value: 0x7f06008f
			public const int msg_mustupload = 2131099791;
			
			// aapt resource value: 0x7f060071
			public const int msg_noitem = 2131099761;
			
			// aapt resource value: 0x7f060066
			public const int msg_plswait = 2131099750;
			
			// aapt resource value: 0x7f060072
			public const int msg_reqcancel = 2131099762;
			
			// aapt resource value: 0x7f060064
			public const int msg_select_cust = 2131099748;
			
			// aapt resource value: 0x7f060065
			public const int msg_select_item = 2131099749;
			
			// aapt resource value: 0x7f060074
			public const int msg_successdowncusts = 2131099764;
			
			// aapt resource value: 0x7f060077
			public const int msg_successdowndb = 2131099767;
			
			// aapt resource value: 0x7f060073
			public const int msg_successdownitems = 2131099763;
			
			// aapt resource value: 0x7f060078
			public const int msg_successdownlogo = 2131099768;
			
			// aapt resource value: 0x7f060076
			public const int msg_successdownprofile = 2131099766;
			
			// aapt resource value: 0x7f060075
			public const int msg_successdownrunno = 2131099765;
			
			// aapt resource value: 0x7f060079
			public const int msg_successdowntmp = 2131099769;
			
			// aapt resource value: 0x7f06007e
			public const int msg_trxclear = 2131099774;
			
			// aapt resource value: 0x7f06006f
			public const int msg_upload = 2131099759;
			
			// aapt resource value: 0x7f06006c
			public const int msg_uploadcn = 2131099756;
			
			// aapt resource value: 0x7f06006d
			public const int msg_uploaddo = 2131099757;
			
			// aapt resource value: 0x7f060068
			public const int msg_uploading = 2131099752;
			
			// aapt resource value: 0x7f06006b
			public const int msg_uploadinv = 2131099755;
			
			// aapt resource value: 0x7f06006e
			public const int msg_uploadso = 2131099758;
			
			// aapt resource value: 0x7f06005a
			public const int paid_billamount = 2131099738;
			
			// aapt resource value: 0x7f06005e
			public const int paid_change = 2131099742;
			
			// aapt resource value: 0x7f06005d
			public const int paid_paying = 2131099741;
			
			// aapt resource value: 0x7f06005b
			public const int paid_roundadj = 2131099739;
			
			// aapt resource value: 0x7f06005c
			public const int paid_totaldue = 2131099740;
			
			// aapt resource value: 0x7f060010
			public const int submenu_back = 2131099664;
			
			// aapt resource value: 0x7f06000b
			public const int submenu_cash = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int submenu_cn = 2131099661;
			
			// aapt resource value: 0x7f060013
			public const int submenu_cnlist = 2131099667;
			
			// aapt resource value: 0x7f060018
			public const int submenu_cust = 2131099672;
			
			// aapt resource value: 0x7f06000e
			public const int submenu_do = 2131099662;
			
			// aapt resource value: 0x7f060014
			public const int submenu_dolist = 2131099668;
			
			// aapt resource value: 0x7f06001b
			public const int submenu_downcust = 2131099675;
			
			// aapt resource value: 0x7f06001a
			public const int submenu_downitem = 2131099674;
			
			// aapt resource value: 0x7f06001c
			public const int submenu_downsettings = 2131099676;
			
			// aapt resource value: 0x7f06000c
			public const int submenu_inv = 2131099660;
			
			// aapt resource value: 0x7f060011
			public const int submenu_invcash = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int submenu_invlist = 2131099666;
			
			// aapt resource value: 0x7f060017
			public const int submenu_item = 2131099671;
			
			// aapt resource value: 0x7f060090
			public const int submenu_pos = 2131099792;
			
			// aapt resource value: 0x7f06000f
			public const int submenu_so = 2131099663;
			
			// aapt resource value: 0x7f060015
			public const int submenu_solist = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int submenu_summary = 2131099670;
			
			// aapt resource value: 0x7f060019
			public const int submenu_testprint = 2131099673;
			
			// aapt resource value: 0x7f060021
			public const int submenu_upall = 2131099681;
			
			// aapt resource value: 0x7f06001e
			public const int submenu_upcn = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int submenu_updo = 2131099679;
			
			// aapt resource value: 0x7f06001d
			public const int submenu_upinv = 2131099677;
			
			// aapt resource value: 0x7f060020
			public const int submenu_upso = 2131099680;
			
			// aapt resource value: 0x7f060044
			public const int title_barcode = 2131099716;
			
			// aapt resource value: 0x7f06003f
			public const int title_cash = 2131099711;
			
			// aapt resource value: 0x7f060041
			public const int title_cashedit = 2131099713;
			
			// aapt resource value: 0x7f060043
			public const int title_cashitementry = 2131099715;
			
			// aapt resource value: 0x7f060042
			public const int title_cashitems = 2131099714;
			
			// aapt resource value: 0x7f060040
			public const int title_cashnew = 2131099712;
			
			// aapt resource value: 0x7f06004e
			public const int title_cnitementry = 2131099726;
			
			// aapt resource value: 0x7f06004a
			public const int title_creditnote = 2131099722;
			
			// aapt resource value: 0x7f06004b
			public const int title_creditnoteedit = 2131099723;
			
			// aapt resource value: 0x7f06004c
			public const int title_creditnoteitems = 2131099724;
			
			// aapt resource value: 0x7f06004d
			public const int title_creditnotenew = 2131099725;
			
			// aapt resource value: 0x7f060055
			public const int title_do = 2131099733;
			
			// aapt resource value: 0x7f060056
			public const int title_doedit = 2131099734;
			
			// aapt resource value: 0x7f060059
			public const int title_doitementry = 2131099737;
			
			// aapt resource value: 0x7f060057
			public const int title_doitems = 2131099735;
			
			// aapt resource value: 0x7f060058
			public const int title_donew = 2131099736;
			
			// aapt resource value: 0x7f060049
			public const int title_invitementry = 2131099721;
			
			// aapt resource value: 0x7f060045
			public const int title_invoice = 2131099717;
			
			// aapt resource value: 0x7f060047
			public const int title_invoiceedit = 2131099719;
			
			// aapt resource value: 0x7f060048
			public const int title_invoiceitems = 2131099720;
			
			// aapt resource value: 0x7f060046
			public const int title_invoicenew = 2131099718;
			
			// aapt resource value: 0x7f06004f
			public const int title_payment = 2131099727;
			
			// aapt resource value: 0x7f060050
			public const int title_so = 2131099728;
			
			// aapt resource value: 0x7f060051
			public const int title_soedit = 2131099729;
			
			// aapt resource value: 0x7f060054
			public const int title_soitementry = 2131099732;
			
			// aapt resource value: 0x7f060052
			public const int title_soitems = 2131099730;
			
			// aapt resource value: 0x7f060053
			public const int title_sonew = 2131099731;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int AutoCompleteTextViewBlueThem = 2131230720;
			
			// aapt resource value: 0x7f08000c
			public const int BlueThem = 2131230732;
			
			// aapt resource value: 0x7f080001
			public const int ButtonBlueThem = 2131230721;
			
			// aapt resource value: 0x7f080004
			public const int EditTextBlueThem = 2131230724;
			
			// aapt resource value: 0x7f080002
			public const int ImageButtonBlueThem = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int SpinnerBlueThem = 2131230723;
			
			// aapt resource value: 0x7f080005
			public const int SpinnerItemBlueThem = 2131230725;
			
			// aapt resource value: 0x7f080007
			public const int XamActionBarStyle = 2131230727;
			
			// aapt resource value: 0x7f080006
			public const int XamActionBarTheme = 2131230726;
			
			// aapt resource value: 0x7f080008
			public const int XamActionBarTitleStyle = 2131230728;
			
			// aapt resource value: 0x7f08000b
			public const int XamButton = 2131230731;
			
			// aapt resource value: 0x7f08000a
			public const int XamSubtitleText = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int XamTitleText = 2131230729;
			
			// aapt resource value: 0x7f08000d
			public const int _BlueThem = 2131230733;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
